language: node_js
cache: # información ya configurada para el proyecto
        directories:
                - node_modules
                - ~/.npm
node_js: #version
        - '12'
git: # número de versiones (git) a guardar
        depth: 3
script: #script a ejecutar
        - yarn build
notifications:
  email:
    reciepients:
    - 1005alexis@gmail.com
    - alexis_oc@yahoo.es
    on_success: always
    on_failure: always
# manda emails a esos mails cuando es exitoso y cuando falla
deploy:
        provider: pages #github pages
# configuración del deploy:
        skip_cleanup: true
        keep_history: true
# creación de un token para la conexión
# entre Travis y GitHub:
        github_token: $GITHUB_TOKEN
# directorio resultante de la compilación:
# xej: /bodndel  /public ...etc
        local_dir: dist/
# rama de publicación (sitio) de GitHub:
        tarjet_branch: gh-pages
        commit_message: "Deploy del proyecto travis"
        on:
                branch: master